openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /jobs:
    get:
      summary: Returns a list of jobs.
      responses:
        '200':    # status code
          description: A list of jobs
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

components:
    schemas:
        Job:
            properties:
                id:
                    type: string
                created:
                    type: integer
                
