openapi: 3.0.0
info:
  title: Sample API
  description: Orchestration backend for AI Brush
  version: 1.0.0
servers:
  - url: https://qb1eyw689j.execute-api.us-east-1.amazonaws.com/Prod
  - url: /
paths:
  /jobs:
    get:
      summary: Returns a list of jobs.
      operationId: listJobs
      responses:
        '200':    # status code
          description: A list of jobs
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

components:
  schemas:
    Job:
      properties:
        id:
          type: string
        created:
          type: integer
        phrases:
          type: array
          items:
            type: string
        parent:
          type: string
        label:
          type: string
        count:
          type: integer
    JobInput:
      properties:
        
          
