openapi: 3.0.0
tags:
  - name: AIBrush

info:
  title: Sample API
  description: Orchestration backend for AI Brush
  version: 1.0.0
  contact:
    email: wolfgangmeyers@gmail.com
servers:
  - url: https://qb1eyw689j.execute-api.us-east-1.amazonaws.com/Prod
  - url: /
paths:
  /jobs:
    get:
      description: Returns a list of jobs.
      operationId: listJobs
      tags:
        - AIBrush
      responses:
        '200':    # status code
          description: A list of jobs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobList"
    post:
      description: Create a new job
      operationId: createJob
      tags:
        - AIBrush
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JobInput"
      responses:
        '201':
          description: Job created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Job"
  /jobs/{id}:
    get:
      description: Get a single job
      operationId: getJob
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - AIBrush
      responses:
        "200":
          description: Job
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Job"
    delete:
      description: Delete a job
      operationId: deleteJob
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - AIBrush
      responses:
        "204":
          description: Success

components:
  schemas:
    Job:
      properties:
        id:
          type: string
        created:
          type: integer
        phrases:
          type: array
          items:
            type: string
        parent:
          type: string
        label:
          type: string
        count:
          type: integer
        iterations:
          type: integer
    JobInput:
      required:
        - phrases
        - count
      properties:
        phrases:
          type: array
          items:
            type: string
        parent:
          type: string
        label:
          type: string
        count:
          type: integer
        iterations:
          type: integer
    JobList:
      properties:
        jobs:
          type: array
          items:
            $ref: "#/components/schemas/Job"

